.. note:: The Subjects API v1 has been DEPRECATED in the Newton release.  The
    migration path is to use the `Subjects API v2
    <http://developer.openstack.org/api-ref/subject/v2/>`_ instead of version 1
    of the API.  The Subjects API v1 will ultimately be removed, following the
    `OpenStack standard deprecation policy
    <https://governance.openstack.org/reference/tags/assert_follows-standard-deprecation.html>`_.
